# install chefdk for testing
install:
  - wget https://packages.chef.io/stable/ubuntu/12.04/chefdk_0.18.26-1_amd64.deb
  - sudo dpkg -i chefdk_0.18.26-1_amd64.deb
# run all rake tasks (lint and style)
script: rake
